Fix get_disabled_quotas
Disabled quotas should be treated as a set, not as a list, or else
instead of action buttons we'll get a traceback:

File "/manila-ui/manila_ui/dashboards/project/shares/__init__.py",
    line 129, in get_disabled_quotas
    disabled_quotas.extend(_get_manila_disabled_quotas(request))
AttributeError: 'set' object has no attribute 'extend'

Change-Id: I5364a8b7fbea3f166264c33ffb6eff341e140bdf
Closes-Bug: #1611368