Workaround SDK bug in listing shares
python-manilaclient 3.3.0 [1] has a bug that causes the shares
panel to fail to load with an error:

Error: Unable to retrieve share list. Details
'NoneType' object has no attribute 'pop'

Workaround this problem so we don't have to add the client
version to a block-list in the UI's requirements files.

Closes-Bug: #1967312
[1] https://pypi.org/project/python-manilaclient/3.3.0/

Change-Id: I9e79972d9aca4fc7845f4d274751351d948f41ef
Signed-off-by: Goutham Pacha Ravi <gouthampravi@gmail.com>